### ISSUE TITLE
Certbot checkout fails with "error: pathspec 'v0.8.1' did not match any file(s) known to git."

### ISSUE THREAD

**Issue by brennen** [jaywink/ansible-letsencrypt#19]
I had to zap [the `depth: 1` in `tasks/client.yaml`](https://github.com/jaywink/ansible-letsencrypt/blob/master/tasks/client.yaml#L22) in order to fix this:

```yaml
fatal: [example.com]: FAILED! => {
    "changed": false, 
    "cmd": "/usr/bin/git checkout --force v0.8.1", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "accept_hostkey": false, 
            "bare": false, 
            "clone": true, 
            "depth": 1, 
            "dest": "/opt/certbot", 
            "executable": null, 
            "force": true, 
            "key_file": null, 
            "recursive": true, 
            "reference": null, 
            "refspec": null, 
            "remote": "origin", 
            "repo": "https://github.com/certbot/certbot", 
            "ssh_opts": null, 
            "track_submodules": false, 
            "umask": null, 
            "update": true, 
            "verify_commit": false, 
            "version": "v0.8.1"
        }, 
        "module_name": "git"
    }, 
    "msg": "Failed to checkout v0.8.1", 
    "rc": 1, 
    "stderr": "error: pathspec 'v0.8.1' did not match any file(s) known to git.\n", 
    "stdout": "", 
    "stdout_lines": []
}
```

My guess is this was probably not failing earlier, when v0.8.1 was current.
