### ISSUE TITLE
Multiple domain validation

### ISSUE THREAD

**Issue by gagath** [jaywink/ansible-letsencrypt#27]
Thanks for this role, I have managed to run this and have certbot to generate SSL stuff. Great.

I understand that I can run multiple subdomains validation with the following:

```yaml
- role: jaywink.letsencrypt
  letsencrypt_domain: domain1.example.com
  letsencrypt_email: example@example.com
- role: jaywink.letsencrypt
  letsencrypt_domain: domain1.example.com
  letsencrypt_email: example@example.com
```

However this is going to go each time throught the whole process of updating certbot and then requesting validation. What I think could be implemented is something like this:

```yaml
- role: jaywink.letsencrypt
  letsencrypt_entries:
    - letsencrypt_domain: domain1.example.com
      letsencrypt_email: example@example.com
    - letsencrypt_domain: domain2.example.com
      letsencrypt_email: example@example.com
    - letsencrypt_domain: domain3.example.com
      letsencrypt_email: example@example.com
```
